--ALTER SYSTEM SET PLSQL_WARNINGS='DISABLE:ALL';
--ALTER SESSION SET PLSQL_WARNINGS='DISABLE:SEVERE';

--DROP PROCEDURE cant_go_there
create PROCEDURE cant_go_there
 AUTHID CURRENT_USER
 AS 
 l_salary NUMBER := 10000; 
 BEGIN
  IF l_salary > 20000 THEN
    DBMS_OUTPUT.put_line ('Executive');
  ELSE
    DBMS_OUTPUT.put_line ('Rest of Us');
  END IF;
END cant_go_there;
/

ALTER SESSION SET PLSQL_WARNINGS='DISABLE:SEVERE','ENABLE:PERFORMANCE','ERROR:05005';
CREATE OR REPLACE FUNCTION no_return RETURN VARCHAR2
 AS
 BEGIN
  DBMS_OUTPUT.PUT_LINE ('Here I am, here I stay');
 END no_return;
/

SHOW ERR
